### PR TITLE
lualine: increase theme compatibility; fix component definitions

### PR DESCRIPTION
**Pull request by NotAShelf**
Successor PR of #290. 

- Cleans up Lualine module as per @balkenix's original PR.
- Fixes blending issue in section separators
- Fixes edited/read-only icons taking less space than they are supposed to.

### CODE REVIEW

**Comment by balkenix** [comment]
Thanks! I was going to do this within the hour but I got caught up.

**Review by FrothyMarrow — APPROVED** [review]
LGTM

**Review by balkenix — APPROVED** [review]
:+1: These all look good and are a definite improvement on my version of it, cheers again!

**Comment by NotAShelf** [comment]
Thanks for the feedback everyone, merging.

**Pull request merged**
