### PR TITLE
Emac

### PR DESCRIPTION
**Pull request by jacekpoz**
Emac

### CODE REVIEW

**Comment by xStormyy** [comment]
emac

**Review by NotAShelf — APPROVED** [review]
emac

**Comment by jacekpoz** [comment]
GNU Emac

**Comment by xStormyy** [comment]
GNU slash emacks

**Comment by NotAShelf** [comment]
waiting for emaci to pass

**Comment by jacekpoz** [comment]
All emac have passed

**Comment by NotAShelf** [comment]
thanks for the emac 👍🏻

**Comment by jacekpoz** [comment]
Emac

**Comment by roastedcheese** [comment]
Emac

**Pull request merged**
