### PR TITLE
lsp/otter: init

### PR DESCRIPTION
**Pull request by Soliprem**
# Description

Adds Support for the Otter plugin. Added an assert to prevent ccc and otter from being enabled simultaneously. Currently set Otter as on by default in Maximal config.

## Type of change

- New feature (non-breaking change which adds functionality)

### Note
If Otter and ccc are both enabled, there'll be an assert

## Checklist

Please try to check at least a majority of the checklist before opening your pull request. Exceptions to this will be reviewed on a case by case basis.

- [X] My code follows the style and contributing guidelines of this project.
- [X] I ran Alejandra to format my code (`nix fmt`).
- [X] I have performed a self-review of my own code and tested it.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] This change requires a documentation update.
- [ ] I have updated the documentation accordingly.

## Screenshots & Logs

image

### CODE REVIEW

**Comment by Soliprem** [comment]
Huh, not sure why it's also showing the old r commits, those have already been merged and are from another branch. No r files are being changed in this PR

**Comment by NotAShelf** [comment]
> Huh, not sure why it's also showing the old r commits, those have already been merged and are from another branch. No r files are being changed in this PR

Your branch is missing changes in the main branch. Fetch `main` from this repository, and merge it into your branch.

Usually this would be adding a new remote (e.g. upstream) and running `git pull upstream main --rebase`

**Review by NotAShelf — CHANGES_REQUESTED** [review]
Overall LGTM. However I'd rather if the option was called `otter-nvim` since the name of the plugin is `otter.nvim`. This would also be more in line with the name of the input.

Left some review comments.

**Comment by Soliprem** [comment]
Done and tested it locally. All ok with the setupOpts implementation? I've never done it before

**Review by NotAShelf — APPROVED** [review]

**Review by NotAShelf — APPROVED** [review]

**Comment by NotAShelf** [comment]
All looks good. I'll merge once the CI passes.

**Comment by NotAShelf** [comment]
thank you :)

**Pull request merged**
