### PR TITLE
v0.7

### PR DESCRIPTION
**Pull request by NotAShelf**
## Branchout for 0.7

- Until this PR is merged, any new features must target the `v0.7` branch to minimize merge conflicts.
- Breaking changes must be disclosed, and remedied: if something broke, it should be documented.
- Here be dragons! Expect unstable behaviour until this is merged, and especially if the PR is a draft.

## Significant Changes

For changes not documented here, see the changelog. This section only mentions large, breaking changes that are worth noting. For changes not mentioned here, please see the change-log.

1. Maps rewrite (#352 and #360)
2. Lazy-loading support (#407)
3. Base16 theming (#389)
4. Completion rewrite, Luasnip (#398)
5. New Language Modules
   - Kotlin support (#390)
   - Scala support (#399)
   - Neorg support (#413)
   - C# support (#428)
   - Julia support (#431)
   - Vala support (#432)
   - ASM support (#447) 
6. Rewrite of Visual modules (#442) 
   - Some options have been renamed, `vim.visuals.enable` removed
7. All plugin inputs have been bumped to their absolute latest revisions.
8. Documentation improvements, cleanup (#440)
9. Deprecation of `vim.leaderKey` and similar `vim.*` options in favor of a migration to `vim.options` and `vim.globals` (#455)

### CODE REVIEW

**Comment by NotAShelf** [comment]
Removing the "draft" status as most blocking changes are now merged, and in need of feedback.

**Review by Soliprem — APPROVED** [review]
LGTM (lets get this merged)

**Review by NotAShelf — COMMENTED** [review]
LGTM (insightful review)

**Review by diniamo — APPROVED** [review]

**Review by horriblename — COMMENTED** [review]
LGTM (CI said so)

**Review by horriblename — APPROVED** [review]

**Pull request merged**
