### PR TITLE
R: adding LSP

### PR DESCRIPTION
**Pull request by Soliprem**
Adding LSP support for R. 
Can't get treesitter to work, but am including what I have so far (commenting out the activation) so someone else might give it a look. I must be missing something

### CODE REVIEW

**Comment by NotAShelf** [comment]
Everything LGTM. I'm not sure why treesitter grammar would not work (but I can make a guess basede on the state of treesitter packaging.)

Are there any errors when you enable the treesitter grammar? Or does it simply not highlight anything?

**Comment by NotAShelf** [comment]
Ah, I see the issue.

You should define treesitter.package with `mkGrammarOption`:

```nix
treesitter = {
      enable = mkEnableOption "R treesitter" // {default = config.vim.languages.enableTreesitter;};
      package = mkGrammarOption pkgs "r";
};
```

**Comment by Soliprem** [comment]
Testing it locally gives me the same error:

**Comment by Soliprem** [comment]
image

**Comment by Soliprem** [comment]
Mind you, highlighting works, but I suspect it might be falling back onto the native syntax highlighting

**Comment by NotAShelf** [comment]
Does maximal configuration work?

**Comment by Soliprem** [comment]
I'm testing the binary generated with nix build .#maximal

**Comment by NotAShelf** [comment]
Okay I ran into it as well. My best bet would be that either
a. the grammar is outdated (trying with a newer nixpkgs revision now)
or
b. the grammar is just faulty

**Comment by Soliprem** [comment]
in case of a, we can just wait for a new nixpkgs version, in case of b I guess we just take out treesitter from the module?

**Comment by NotAShelf** [comment]
We could get rid of the treesitter package and opt in for the LSP only. Appears that it's *not* the nixpkgs revision, unless it's an issue with TS packaging.

**Comment by Soliprem** [comment]
huh, might want to report it on the nixpkgs repo as a bug with the package, then. In the meantime, I'd simply edit the PR to only include the LSP. Coming within a few minutes.

**Comment by Soliprem** [comment]
is there any indication that beyond the error Treesitter was working? I didn't really know how to check, beyond running checkhealth, which didn't return anything interesting

**Comment by NotAShelf** [comment]
My best guess is that the TS grammar is outdated. I'll try overriding the source and see if that is the case.

**Comment by NotAShelf** [comment]
The *built* grammar seems to work. Not what I hoped would be the solution, but we can easily resolve the TS issue by using a built grammar it seems...

**Comment by Soliprem** [comment]
Implementation-wise how does that work?

**Comment by Soliprem** [comment]
wasn't that the content of the original PR? Using ```pkgs.vimPlugins.nvim-treesitter.builtGrammars.r``` ?

**Review by NotAShelf — CHANGES_REQUESTED** [review]
LGTM, but needs changelog entry added before I can merge this.

**Review by NotAShelf — APPROVED** [review]

**Comment by NotAShelf** [comment]
Merging once CI passes.

**Comment by NotAShelf** [comment]
thank you :)

**Pull request merged**
