### PR TITLE
lualine: limit catppuccin reliance; update flake inputs

### PR DESCRIPTION
**Pull request by balkenix**
# Why did I make these changes?
Lockfile: Neovim Nightly broke `noice.nvim`'s LSP progress function. This was fixed upstream but it should be updated here too.
Catppuccin Reliance: It caused every theme that wasnt catppuccin to break into this ugly mess lmao 

Catppuccin overreliance may also exist in other files too but I'll feel compelled enough to check come the weekends.

### CODE REVIEW

**Review by FrothyMarrow — COMMENTED** [review]
Looks good, please add a changelog entry to`0.7.md` in docs.

**Comment by balkenix** [comment]
I'll get on it :+1:

**Comment by NotAShelf** [comment]
Looks good. Glad to finally have this addressed. Just one minor nit:

Please follow the commit format as [specified in the documentation](https://notashelf.github.io/nvf/index.xhtml#sec-guidelines-commit-style). In your case, it should be squashed into three commits.

For lualine module:
```
lualine: limit catppuccin reliance
```
For `flake.nix`:
```
flake: update inputs
```

For docs:
```
docs: update 0.7 release notes
```

**Comment by balkenix** [comment]
ill probably set up another pr because right now im horrible at git lmao

ill try to figure something out without creating 4 new fake commits, it'll look like artificial commit increasing which is something i do not want

**Comment by balkenix** [comment]
alright yeah i dont think this is possible, ill make another pr

**Comment by NotAShelf** [comment]
I would rebase, but looks like flake update and lualine changes have been done in the smae commit.

**Comment by balkenix** [comment]
yeah thats the problem lmao

**Comment by NotAShelf** [comment]
I was meaning to clean up lualine for a while now. I think I'll create a PR myself to address your issues and my own.

**Comment by NotAShelf** [comment]
Created #291.

**Pull request closed without merging**
