### PR TITLE
fix buildPlug patches, update mnw

### PR DESCRIPTION
**Pull request by Gerg-L**
@FrothyMarrow can you test if flutter-tools works with this setup
your change of copying `$src` breaks `patches` from doing anything
i was setting version incorrectly though
i switched to `stdenvNoCC.mkDerivation` because it seems nicer in this case

### CODE REVIEW

**Comment by Gerg-L** [comment]
also updated mnw because i can

**Comment by FrothyMarrow** [comment]
@Gerg-L Oh yeah I totally forgot about the patch itself. Also, I don't use flutter-tools but I think @Vagahbond can test it out.

**Comment by Vagahbond** [comment]
I do not do Flutter sorry

**Comment by NotAShelf** [comment]
CC @FlafyDev for being a cutie and the one to add the patch

**Comment by NotAShelf** [comment]
Seems to build fine, though I can't verify if the patches have applied. I'll need to test with a dummy flutter project later

**Comment by FlafyDev** [comment]
i can test
can i get nvf with flutter support through a cli command?

**Comment by NotAShelf** [comment]
> i can test can i get nvf with flutter support through a cli command?

Unfortunately, no. But you can initialize a quick configuration using the extended library and a very basic flake:

```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    nvf.url = "github:notashelf/nvf";
  };

  outputs = inputs: let
    system = "x86_64-linux";
    pkgs = inputs.nixpkgs.legacyPackages.${system};

    customNeovim = inputs.nvf.lib.neovimConfiguration {
      inherit pkgs;

      modules = [
        {
          config.vim = {
            languages.dart = {
              enable = true;
              dap.enable = true;
            };
          };
        }
      ];
    };
  in {
    packages.${system}.neovim = customNeovim.neovim;
  };
}
```

**Comment by FlafyDev** [comment]
doesn't seem to work
image

**Comment by NotAShelf** [comment]
My bad I missed a few lines. Please try this @FlafyDev 

```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    nvf.url = "github:gerg-l/nvf";
  };

  outputs = inputs: let
    system = "x86_64-linux";
    pkgs = inputs.nixpkgs.legacyPackages.${system};

    customNeovim = inputs.nvf.lib.neovimConfiguration {
      inherit pkgs;

      modules = [
        {
          config.vim = {
            startPlugins = [pkgs.vimPlugins.plenary-nvim];
            languages.dart = {
              enable = true;
              lsp.enable = false;
              treesitter.enable = true;
              flutter-tools = {
                enable = true;
                color = {
                  enable = true;
                  virtualText.enable = true;
                };
              };
            };
          };
        }
      ];
    };
  in {
    packages.${system}.neovim = customNeovim.neovim;
  };
}
```

**Comment by FlafyDev** [comment]
works 👍 
image

**Pull request merged**
